remote_theme: ISSAE/architect

name: C1 AISL

author: Hussein Mansour

author_email: hussein.mansour@isae.edu.lb

title: Tutoriel de Google Big Table avec API JAVA

google_analytics: UA-29708002-2

plugins:
  - jekyll-sitemap

