remote_theme: ISSAE/architect

name: Portail ISSAE Cnam Liban des cours traveaux et projets

author: Pascal Fares

author_email: pascal.fares@isae.edu.lb

title: Compléments, exercices et projets des Ue informatique Cnam Liban 

google_analytics: UA-29708002-2

plugins:
  - jekyll-sitemap

